url:
broadcastImageUrl: https://cdn.vectorstock.com/i/1000v/43/21/megaphone-icon-vector-21894321.jpg
serverImageUrl: https://e7.pngegg.com/pngimages/981/872/png-clipart-computer-terminal-computer-icons-linux-console-terminal-emulator-linux-logo-desktop-wallpaper-thumbnail.png
debug: false
usePlayerName: true
useSkinRestorer: false